name: integration

permissions: {}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}

jobs:
  lint_test:
    name: Lint & Test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        processor: [satteri, unified]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install pnpm, Node.js, and dependencies
        uses: pnpm/setup@703c52620218391530e48b9e8870d5c0082e1b9b # v2.1.0
        with:
          cache: true

      - name: Build package
        if: matrix.os == 'ubuntu-latest' && matrix.processor == 'satteri'
        run: pnpm build
        working-directory: packages/starlight-links-validator

      - name: Test
        run: pnpm --filter starlight-links-validator test:${{ matrix.processor }}

      - name: Generates docs TypeScript types
        if: matrix.os == 'ubuntu-latest' && matrix.processor == 'satteri'
        run: pnpm astro sync
        working-directory: docs

      - name: Lint
        if: matrix.os == 'ubuntu-latest' && matrix.processor == 'satteri'
        run: pnpm lint
  links:
    name: Check for broken links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install pnpm, Node.js, and dependencies
        uses: pnpm/setup@703c52620218391530e48b9e8870d5c0082e1b9b # v2.1.0
        with:
          cache: true

      - name: Check links
        run: pnpm linkcheck
        working-directory: docs
